In [36]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_wine
from sklearn.metrics import accuracy_score
from sklearn import datasets
from sklearn.datasets import make_regression
import pandas as pd 


In [37]:
dataset = make_regression(n_samples=10000, n_features=30, n_informative=10, n_targets=10, bias=0.0, effective_rank=None, tail_strength=0.5, noise=0.0, shuffle=True, coef=False, random_state=None)

In [38]:
X=dataset[0]
y=dataset[1]

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=10)

In [40]:
dt = DecisionTreeRegressor()
dt.fit(X_train, y_train)
predictions_dt = dt.predict(X_test)

In [41]:
predictions_dt

array([[ -43.16672617, -266.41934904, -151.86730001, ..., -362.50254833,
        -355.54015312, -255.20424052],
       [ 111.49741352,   49.4554205 ,  198.31152831, ...,  -69.96235306,
          56.32115294,  169.94376544],
       [-131.13839905,   13.8271649 ,  212.57778432, ...,   87.77588744,
          75.78116432,  111.10651885],
       ...,
       [  45.0265029 ,  199.43856689,  -35.87671814, ...,  191.42852433,
         165.79404226,   46.80812435],
       [ -12.02622445,   99.01283035,  109.58168197, ...,   93.29766212,
          94.51857769,  141.65130233],
       [  22.03416778,  225.89040304,  290.72150441, ...,  168.81948863,
         220.65544875,  379.39602803]])

In [42]:
from sklearn.metrics import mean_squared_error

In [43]:
mean_squared_error(y_test, predictions_dt), np.sqrt(mean_squared_error(y_test, predictions_dt))

(21288.65984394283, 145.90633928634776)

## Grad boosting

In [8]:
from sklearn.multioutput import MultiOutputRegressor
import time

start = time.time()
params = {'n_estimators': 300, 'max_depth': 3, 'criterion' :'squared_error', 'learning_rate' : 0.1}
estimator = MultiOutputRegressor(GradientBoostingRegressor(**params))
estimator.fit(X_train, y_train)
end = time.time()
diff = end - start
print('Time elapsed', diff)

KeyboardInterrupt: 

In [ ]:
mean_squared_error(y_test, estimator.predict(X_test)), np.sqrt(mean_squared_error(y_test, estimator.predict(X_test)))

In [ ]:
estimator

In [ ]:
y_test[10], estimator.predict(X_test[10].reshape(1, -1))

## LightGBM Grad boosting

In [ ]:
import lightgbm as lgb

In [ ]:
from lightgbm import LGBMRegressor

In [ ]:
lgbm_regressor = LGBMRegressor()

In [ ]:
lgb_start = time.time()
params = {'n_estimators': 300, 'max_depth': 3, 'learning_rate' : 0.1, 'num_leaves': 1000, 'min_child_samples': 1}
# in reality here number_of_trees = n_estimator * number_classes, 3000 trees here? 
lgb_estimator = MultiOutputRegressor(LGBMRegressor(**params))
lgb_estimator.fit(X_train, y_train)
lgb_end = time.time()
lgb_time_diff = lgb_end - lgb_start
print('Time elapsed', lgb_time_diff)

In [ ]:
mean_squared_error(y_test, lgb_estimator.predict(X_test)), np.sqrt(mean_squared_error(y_test, lgb_estimator.predict(X_test)))

---------------------------

In [44]:
feature_df_train = pd.DataFrame(data=X_train)
feature_df_test = pd.DataFrame(data=X_test)

In [45]:
y_train[:3], y_train[:3].T

(array([[ 336.49268415,  386.14614359,  299.65022958,  390.73257687,
          556.25227007,  445.92269859,  499.95734357,  293.76278332,
          487.07619729,  423.47492712],
        [ 128.24905361,   45.12986602,  -71.14501311,  -68.80742948,
          -95.20034827,   42.6026197 ,   18.4005077 ,   47.36687973,
           54.09498611,  -75.06322765],
        [  52.8273343 ,  -98.57012489,   -9.08915993, -147.17948157,
           33.93706033,  -13.32675618,  -79.89338201, -292.32139318,
          -98.86297582,   53.53199938]]),
 array([[ 336.49268415,  128.24905361,   52.8273343 ],
        [ 386.14614359,   45.12986602,  -98.57012489],
        [ 299.65022958,  -71.14501311,   -9.08915993],
        [ 390.73257687,  -68.80742948, -147.17948157],
        [ 556.25227007,  -95.20034827,   33.93706033],
        [ 445.92269859,   42.6026197 ,  -13.32675618],
        [ 499.95734357,   18.4005077 ,  -79.89338201],
        [ 293.76278332,   47.36687973, -292.32139318],
        [ 487.07619729, 

In [46]:
labels_df_train = pd.DataFrame()
for label_column_index in range(len(y_train.T)):
    label_column = y_train.T[label_column_index]
    labels_df_train[label_column_index] = label_column

In [47]:
labels_df_test = pd.DataFrame()
for label_column_index in range(len(y_test.T)):
    label_column = y_test.T[label_column_index]
    labels_df_test[label_column_index] = label_column

In [48]:
features_test_path = '/Users/daraghking/Documents/Thesis/Code/Rust/grad_boost_mcc/tree_learner/common/data-files/multi-target/features_test_mt.csv'
features_train_path = '/Users/daraghking/Documents/Thesis/Code/Rust/grad_boost_mcc/tree_learner/common/data-files/multi-target/features_train_mt.csv'

In [49]:
labels_test_path = '/Users/daraghking/Documents/Thesis/Code/Rust/grad_boost_mcc/tree_learner/common/data-files/multi-target/labels_test_mt.csv'
labels_train_path = '/Users/daraghking/Documents/Thesis/Code/Rust/grad_boost_mcc/tree_learner/common/data-files/multi-target/labels_train_mt.csv'

In [50]:
feature_df_train.to_csv(features_train_path, sep = ',', index = False)
feature_df_test.to_csv(features_test_path, sep = ',', index = False)
labels_df_train.to_csv(labels_train_path, sep = ',', index = False)
labels_df_test.to_csv(labels_test_path, sep = ',', index = False)

In [51]:
y_test[0]

array([-289.06429787, -541.27129263, -455.02537371, -488.38788197,
       -506.05526928, -481.03529463, -539.06202499, -576.54649631,
       -678.30758931, -542.94238055])

In [52]:
first_prediction = dt.predict(X_test[0].reshape(1, -1))
first_prediction

array([[ -43.16672617, -266.41934904, -151.86730001, -186.16975833,
        -177.64709129, -288.32328659, -342.73139678, -362.50254833,
        -355.54015312, -255.20424052]])